import type { MenuItem, Order } from "./elevate-orders-types";

export const menuItems: MenuItem[] = [
  {
    id: "italian-stack",
    name: "The Italian Stack",
    description: "Genoa salami, capicola, provolone, shredded lettuce, tomato, onion, and house vinaigrette.",
    price: 14.5,
    category: "Sandwiches",
    popular: true,
    available: true,
    accent: "#f1c6a8",
    initials: "IS",
    image: "/menu/italian-stack.jpg",
    ingredients: ["Genoa salami", "capicola", "provolone", "shredded lettuce", "tomato", "red onion", "house vinaigrette", "sesame sub roll"],
    allergens: ["Gluten", "Milk", "Sesame"],
  },
  {
    id: "turkey-club",
    name: "Roasted Turkey Club",
    description: "Roasted turkey, applewood bacon, cheddar, lettuce, tomato, and herb mayo.",
    price: 13.75,
    category: "Sandwiches",
    popular: true,
    available: true,
    accent: "#b9d7c2",
    initials: "TC",
    image: "/menu/turkey-club.jpg",
    ingredients: ["Roasted turkey", "applewood bacon", "cheddar", "lettuce", "tomato", "herb mayonnaise", "toasted country bread"],
    allergens: ["Gluten", "Egg", "Milk"],
  },
  {
    id: "hot-honey-pie",
    name: "Hot Honey Pepperoni",
    description: "Cup-and-char pepperoni, mozzarella, red sauce, pecorino, and hot honey.",
    price: 19,
    category: "Pizza",
    popular: true,
    available: true,
    accent: "#e9a280",
    initials: "HH",
    image: "/menu/hot-honey-pie.jpg",
    ingredients: ["Wheat pizza dough", "tomato sauce", "whole-milk mozzarella", "cup-and-char pepperoni", "pecorino", "hot honey"],
    allergens: ["Gluten", "Milk"],
  },
  {
    id: "garden-pie",
    name: "The Garden Pie",
    description: "Roasted peppers, mushrooms, red onion, olives, mozzarella, and basil.",
    price: 18,
    category: "Pizza",
    vegetarian: true,
    available: true,
    accent: "#9fc0a3",
    initials: "GP",
    image: "/menu/garden-pie.jpg",
    ingredients: ["Wheat pizza dough", "tomato sauce", "mozzarella", "roasted peppers", "mushrooms", "red onion", "black olives", "fresh basil"],
    allergens: ["Gluten", "Milk"],
  },
  {
    id: "chicken-bowl",
    name: "Charred Chicken Bowl",
    description: "Lemon chicken, seasoned rice, cucumber, tomato, pickled onion, feta, and garlic sauce.",
    price: 15.25,
    category: "Bowls",
    popular: true,
    available: true,
    accent: "#d8bd8a",
    initials: "CB",
    image: "/menu/chicken-bowl.jpg",
    ingredients: ["Lemon-herb chicken", "seasoned rice", "cucumber", "tomato", "pickled red onion", "feta", "garlic yogurt sauce"],
    allergens: ["Milk"],
    glutenFree: true,
  },
  {
    id: "market-bowl",
    name: "Market Veggie Bowl",
    description: "Herbed farro, roasted vegetables, chickpeas, greens, feta, and green goddess dressing.",
    price: 14,
    category: "Bowls",
    vegetarian: true,
    available: true,
    accent: "#a8c6ad",
    initials: "MV",
    image: "/menu/market-bowl.jpg",
    ingredients: ["Herbed farro", "roasted zucchini", "roasted peppers", "chickpeas", "mixed greens", "feta", "green goddess dressing"],
    allergens: ["Gluten", "Milk", "Egg"],
  },
  {
    id: "garlic-knots",
    name: "Garlic Knots",
    description: "Six baked knots with garlic butter, parmesan, parsley, and warm marinara.",
    price: 7,
    category: "Sides",
    available: true,
    accent: "#e6cf9b",
    initials: "GK",
    image: "/menu/garlic-knots-v2.jpg",
    ingredients: ["Wheat dough", "garlic butter", "parmesan", "parsley", "marinara sauce"],
    allergens: ["Gluten", "Milk"],
  },
  {
    id: "crispy-potatoes",
    name: "Crispy Potatoes",
    description: "Sea salt, cracked pepper, herbs, and roasted garlic aioli.",
    price: 6.5,
    category: "Sides",
    vegetarian: true,
    available: true,
    accent: "#d6b67c",
    initials: "CP",
    image: "/menu/crispy-potatoes.jpg",
    ingredients: ["Yukon gold potatoes", "olive oil", "sea salt", "black pepper", "rosemary", "roasted garlic aioli"],
    allergens: ["Egg"],
    glutenFree: true,
  },
  {
    id: "blood-orange",
    name: "Blood Orange Soda",
    description: "Sparkling blood orange soda with real cane sugar.",
    price: 3.5,
    category: "Drinks",
    available: true,
    accent: "#e79f80",
    initials: "BO",
    image: "/menu/blood-orange.jpg",
    ingredients: ["Carbonated water", "blood orange juice", "cane sugar", "citric acid"],
    allergens: [],
    glutenFree: true,
  },
];

export const initialOrders: Order[] = [
  {
    id: "EO-1048",
    customer: "Maya R.",
    phone: "(555) 204-8812",
    type: "Pickup",
    items: [
      { name: "The Italian Stack", quantity: 2, notes: "One without onion" },
      { name: "Crispy Potatoes", quantity: 1 },
    ],
    total: 38.66,
    status: "New",
    placedAt: "11:42 AM",
    promiseTime: "12:02 PM",
    source: "AI Assistant",
    allergyNotes: "GLUTEN ALLERGY - avoid cross-contact; use a clean prep area.",
  },
  {
    id: "EO-1047",
    customer: "Andre W.",
    phone: "(555) 817-0931",
    type: "Pickup",
    items: [
      { name: "Hot Honey Pepperoni", quantity: 1 },
      { name: "Garlic Knots", quantity: 1 },
    ],
    total: 28.08,
    status: "Preparing",
    placedAt: "11:35 AM",
    promiseTime: "11:55 AM",
    source: "Online",
  },
  {
    id: "EO-1046",
    customer: "Sofia L.",
    phone: "(555) 611-4409",
    type: "Delivery",
    items: [
      { name: "Charred Chicken Bowl", quantity: 2 },
      { name: "Blood Orange Soda", quantity: 2 },
    ],
    total: 42.04,
    status: "Preparing",
    placedAt: "11:28 AM",
    promiseTime: "12:08 PM",
    source: "AI Assistant",
    address: "42 Cedar Lane, Apt 3B",
    notes: "Ring the side entrance bell.",
  },
  {
    id: "EO-1045",
    customer: "Chris P.",
    phone: "(555) 322-7144",
    type: "Pickup",
    items: [{ name: "Roasted Turkey Club", quantity: 1, notes: "Extra herb mayo" }],
    total: 14.88,
    status: "Ready",
    placedAt: "11:19 AM",
    promiseTime: "11:39 AM",
    source: "Online",
  },
];
